server:
  debug: false
  app_version: 1.0.0
  addr: :5000
  jwt_secret: accesskey
  jwt_refresh_secret: refreshkey

db:
  driver: postgres
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  name: app
  ssl: disable

redis:
  addr: :6379
  password:
  db: 0

cookie:
  access_token:
    secure: false
    http_only: true